name: Deploy to Xserver

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 最新のコードを受け取る
      uses: actions/checkout@v4

    - name: 2. エックスサーバーへ配置する
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: /algoyosuga.com/public_html/veqtor/
        exclude: |
          **/.git*
          **/.git*/**
          **/.github*
          **/.github*/**
          **/.DS_Store
          **/ARTICLE_INDEX.md
          **/STYLE_GUIDE.md
          **/IMAGE_GUIDE.md
